#!/bin/sh
#bash <(curl -L https://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.0_11289/SurveillanceStation-armv8/install_license)


# 1
if grep -q "synosurveillance.synology.com" /etc/hosts; then
  echo "already blocked license server: synosurveillance.synology.com."
else
  echo "add block license server: synosurveillance.synology.com"
  echo "0.0.0.0 synosurveillance.synology.com" | sudo tee -a /etc/hosts
fi


# 2
process_file() {
  local dir="$1"
  local file="$2"
  local url="$3"
  local mode="$4"

  cd "$dir" || exit
  cp ./"$file" ./"$file"_backup
  rm ./"$file"
  wget "$url" -O ./"$file"
  chown SurveillanceStation:SurveillanceStation ./"$file"
  chmod "$mode" ./"$file"
}


/usr/syno/bin/synopkg stop SurveillanceStation
sleep 5


# 3
process_file /var/packages/SurveillanceStation/target/lib  libssutils.so    https://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.0_11289/SurveillanceStation-armv8/libssutils.so     0644
process_file /var/packages/SurveillanceStation/target/sbin sscmshostd       https://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.0_11289/SurveillanceStation-armv8/sscmshostd        0755
process_file /var/packages/SurveillanceStation/target/sbin sscored          https://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.0_11289/SurveillanceStation-armv8/sscored           0755
process_file /var/packages/SurveillanceStation/target/sbin ssdaemonmonitord https://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.0_11289/SurveillanceStation-armv8/ssdaemonmonitord  0755
process_file /var/packages/SurveillanceStation/target/sbin ssexechelperd    https://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.0_11289/SurveillanceStation-armv8/ssexechelperd     0755
process_file /var/packages/SurveillanceStation/target/sbin ssmessaged       https://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.0_11289/SurveillanceStation-armv8/ssmessaged        0755
process_file /var/packages/SurveillanceStation/target/sbin ssroutined       https://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.0_11289/SurveillanceStation-armv8/ssroutined        0755



sleep 5
/usr/syno/bin/synopkg start SurveillanceStation
