#!/bin/sh
#bash <(curl -L hhttps://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.2_11575/SurveillanceStation-x86_64/install_license)


# 屏蔽认证服务器
if grep -q "synosurveillance.synology.com" /etc/hosts; then
  echo "already blocked license server: synosurveillance.synology.com."
else
  echo "add block license server: synosurveillance.synology.com"
  echo "0.0.0.0 synosurveillance.synology.com" | sudo tee -a /etc/hosts
fi


# 定义处理文件的函数
process_file() {
  local dir="$1"
  local file="$2"
  local url="$3"
  local mode="$4"

  cd "$dir" || exit
  cp ./"$file" ./"$file"_backup
  rm ./"$file"
  wget "$url" -O ./"$file"
  chown SurveillanceStation:SurveillanceStation ./"$file"
  chmod "$mode" ./"$file"
}


/usr/syno/bin/synopkg stop SurveillanceStation
sleep 5


# 处理每个文件
process_file /var/packages/SurveillanceStation/target/lib  libssutils.so    hhttps://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.2_11575/SurveillanceStation-x86_64/libssutils.so     0644
process_file /var/packages/SurveillanceStation/target/sbin sscmshostd       hhttps://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.2_11575/SurveillanceStation-x86_64/sscmshostd        0755
process_file /var/packages/SurveillanceStation/target/sbin sscored          hhttps://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.2_11575/SurveillanceStation-x86_64/sscored           0755
process_file /var/packages/SurveillanceStation/target/sbin ssdaemonmonitord hhttps://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.2_11575/SurveillanceStation-x86_64/ssdaemonmonitord  0755
process_file /var/packages/SurveillanceStation/target/sbin ssexechelperd    hhttps://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.2_11575/SurveillanceStation-x86_64/ssexechelperd     0755
process_file /var/packages/SurveillanceStation/target/sbin ssroutined       hhttps://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.2_11575/SurveillanceStation-x86_64/ssroutined        0755
# process_file /var/packages/SurveillanceStation/target/sbin ssrtmpclientd    hhttps://raw.githubusercontent.com/zkymx/surveillance-station-9/refs/heads/main/9.2.2_11575/SurveillanceStation-x86_64/ssrtmpclientd     0755


sleep 5
/usr/syno/bin/synopkg start SurveillanceStation
